// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | FaqsSlice
  | PricingCardsSlice
  | MultipleColumnCardSlice
  | InfoCardsSlice
  | TrustCardsSlice
  | TitleIntroductionSlice
  | MarkdownSlice
  | TwoColumnSlice
  | OneColumnSlice
  | TestimonialsSlice
  | ShowPricesSlice
  | TechnologiesSlice
  | PartnersSlice
  | RoadMapSlice
  | RecommendedCoursesSlice
  | TechnologiesPillsSlice
  | EventCardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * TItle field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description for Social Cards
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * type field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The default type is "website"
   * - **API ID Path**: page.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * Landing url field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.landing_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  landing_url: prismic.KeyTextField;

  /**
   * Padding Bottom field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.padding_bottom
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  padding_bottom: prismic.KeyTextField;

  /**
   * Transparent field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.transparent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  transparent: prismic.BooleanField;

  /**
   * Background field in *Page*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: page.background
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *EventCards → Primary*
 */
export interface EventCardsSliceDefaultPrimary {
  /**
   * Id key field in *EventCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_cards.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Title field in *EventCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Endpoint field in *EventCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_cards.primary.endpoint
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  endpoint: prismic.KeyTextField;

  /**
   * Margin field in *EventCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: event_cards.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for EventCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: EventCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventCards*
 */
type EventCardsSliceVariation = EventCardsSliceDefault;

/**
 * EventCards Shared Slice
 *
 * - **API ID**: `event_cards`
 * - **Description**: EventCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventCardsSlice = prismic.SharedSlice<
  "event_cards",
  EventCardsSliceVariation
>;

/**
 * Primary content in *Faqs → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Title field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Background Color field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background_color: prismic.KeyTextField;

  /**
   * Margin Bottom field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.margin_bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_bottom: prismic.KeyTextField;

  /**
   * Id key field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Title Font Size field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.title_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_font_size: prismic.KeyTextField;

  /**
   * Title Line Height field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.title_line_height
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_line_height: prismic.KeyTextField;

  /**
   * Title Font Weight field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.title_font_weight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_font_weight: prismic.KeyTextField;

  /**
   * Title Color field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_color: prismic.KeyTextField;

  /**
   * Margin Top field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.margin_top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_top: prismic.KeyTextField;

  /**
   * Max Width field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  max_width: prismic.KeyTextField;

  /**
   * As element field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.as_element
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  as_element: prismic.KeyTextField;

  /**
   * Label Weight field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.label_weight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_weight: prismic.KeyTextField;

  /**
   * Label Font Size field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.label_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_font_size: prismic.KeyTextField;

  /**
   * Label Line Height field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.label_line_height
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_line_height: prismic.KeyTextField;

  /**
   * Answer Weight field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.answer_weight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer_weight: prismic.KeyTextField;

  /**
   * Answer Font Size field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.answer_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer_font_size: prismic.KeyTextField;

  /**
   * Answer Line Height field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.answer_line_height
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer_line_height: prismic.KeyTextField;
}

/**
 * Primary content in *Faqs → Items*
 */
export interface FaqsSliceDefaultItem {
  /**
   * Label field in *Faqs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Answer field in *Faqs → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  Simplify<FaqsSliceDefaultItem>
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *InfoCards → Primary*
 */
export interface InfoCardsSliceDefaultPrimary {
  /**
   * title field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * description field in *InfoCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * cardOneIcon field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardOneIcon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardOneIcon: prismic.KeyTextField;

  /**
   * cardOneColor field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardOneColor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardOneColor: prismic.KeyTextField;

  /**
   * cardOneTitle field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardOneTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardOneTitle: prismic.KeyTextField;

  /**
   * cardOneDescription field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardOneDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardOneDescription: prismic.KeyTextField;

  /**
   * cardTwoIcon field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardTwoIcon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTwoIcon: prismic.KeyTextField;

  /**
   * cardTwoColor field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardTwoColor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTwoColor: prismic.KeyTextField;

  /**
   * cardTwoTitle field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardTwoTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTwoTitle: prismic.KeyTextField;

  /**
   * cardTwoDescription field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardTwoDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardTwoDescription: prismic.KeyTextField;

  /**
   * cardThreeIcon field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardThreeIcon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardThreeIcon: prismic.KeyTextField;

  /**
   * cardThreeColor field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardThreeColor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardThreeColor: prismic.KeyTextField;

  /**
   * cardThreeTitle field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardThreeTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardThreeTitle: prismic.KeyTextField;

  /**
   * cardThreeDescription field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardThreeDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardThreeDescription: prismic.KeyTextField;

  /**
   * cardFourIcon field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardFourIcon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardFourIcon: prismic.KeyTextField;

  /**
   * cardFourColor field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardFourColor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardFourColor: prismic.KeyTextField;

  /**
   * cardFourTitle field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardFourTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardFourTitle: prismic.KeyTextField;

  /**
   * cardFourDescription field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.cardFourDescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardFourDescription: prismic.KeyTextField;

  /**
   * Margin field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;

  /**
   * Padding field in *InfoCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  padding: prismic.KeyTextField;

  /**
   * Font Family field in *InfoCards → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Lato
   * - **API ID Path**: info_cards.primary.fontFamily
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  fontFamily: prismic.SelectField<"Lato" | "Space Grotesk Variable", "filled">;
}

/**
 * Default variation for InfoCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoCards*
 */
type InfoCardsSliceVariation = InfoCardsSliceDefault;

/**
 * InfoCards Shared Slice
 *
 * - **API ID**: `info_cards`
 * - **Description**: InfoCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoCardsSlice = prismic.SharedSlice<
  "info_cards",
  InfoCardsSliceVariation
>;

/**
 * Primary content in *Markdown → Primary*
 */
export interface MarkdownSliceDefaultPrimary {
  /**
   * ID Key field in *Markdown → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Title field in *Markdown → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Markdown → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Markdown field in *Markdown → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown.primary.markdown
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  markdown: prismic.RichTextField;

  /**
   * Enable Table of Content field in *Markdown → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: markdown.primary.enable_table_of_content
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  enable_table_of_content: prismic.BooleanField;

  /**
   * Margin field in *Markdown → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: markdown.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;

  /**
   * Padding field in *Markdown → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: markdown.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  padding: prismic.KeyTextField;
}

/**
 * Default variation for Markdown Slice
 *
 * - **API ID**: `default`
 * - **Description**: Markdown
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarkdownSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarkdownSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Markdown*
 */
type MarkdownSliceVariation = MarkdownSliceDefault;

/**
 * Markdown Shared Slice
 *
 * - **API ID**: `markdown`
 * - **Description**: Markdown
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarkdownSlice = prismic.SharedSlice<
  "markdown",
  MarkdownSliceVariation
>;

/**
 * Primary content in *MultipleColumnCard → Primary*
 */
export interface MultipleColumnCardSliceDefaultPrimary {
  /**
   * Title field in *MultipleColumnCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Id key field in *MultipleColumnCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Font Family Title field in *MultipleColumnCard → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.primary.font_family_title
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  font_family_title: prismic.SelectField<"Lato" | "Space Grotesk Variable">;

  /**
   * Margin Bottom field in *MultipleColumnCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.primary.margin_bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_bottom: prismic.KeyTextField;

  /**
   * Margin Top field in *MultipleColumnCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.primary.margin_top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_top: prismic.KeyTextField;

  /**
   * Max Width field in *MultipleColumnCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  max_width: prismic.KeyTextField;
}

/**
 * Primary content in *MultipleColumnCard → Items*
 */
export interface MultipleColumnCardSliceDefaultItem {
  /**
   * Column Title field in *MultipleColumnCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.items[].column_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_title: prismic.KeyTextField;

  /**
   * Column Description field in *MultipleColumnCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.items[].column_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  column_description: prismic.KeyTextField;

  /**
   * Font Family Column field in *MultipleColumnCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: multiple_column_card.items[].font_family_column
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  font_family_column: prismic.SelectField<"Lato" | "Space Grotesk Variable">;
}

/**
 * Default variation for MultipleColumnCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultipleColumnCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MultipleColumnCardSliceDefaultPrimary>,
  Simplify<MultipleColumnCardSliceDefaultItem>
>;

/**
 * Slice variation for *MultipleColumnCard*
 */
type MultipleColumnCardSliceVariation = MultipleColumnCardSliceDefault;

/**
 * MultipleColumnCard Shared Slice
 *
 * - **API ID**: `multiple_column_card`
 * - **Description**: MultipleColumnCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MultipleColumnCardSlice = prismic.SharedSlice<
  "multiple_column_card",
  MultipleColumnCardSliceVariation
>;

/**
 * Primary content in *OneColumn → Primary*
 */
export interface OneColumnSliceDefaultPrimary {
  /**
   * ID Key field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Margin Top field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.margin_top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_top: prismic.KeyTextField;

  /**
   * Margin Bottom field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.margin_bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_bottom: prismic.KeyTextField;

  /**
   * Max Width field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  max_width: prismic.KeyTextField;

  /**
   * Border Radius field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.border_radius
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  border_radius: prismic.KeyTextField;

  /**
   * Font Family field in *OneColumn → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Lato
   * - **API ID Path**: one_column.primary.font_family
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  font_family: prismic.SelectField<"Lato" | "Space Grotesk Variable", "filled">;

  /**
   * Title field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Title Font Size field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.title_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_font_size: prismic.KeyTextField;

  /**
   * SubTitle field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *OneColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Description Font Size field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.description_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_font_size: prismic.KeyTextField;

  /**
   * Description Text Align field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.description_text_align
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_text_align: prismic.KeyTextField;

  /**
   * Description Justify Items field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.description_justify_items
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_justify_items: prismic.KeyTextField;

  /**
   * Description Line Height field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.description_line_height
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_line_height: prismic.KeyTextField;

  /**
   * Button label field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Background Color field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.button_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_background_color: prismic.ColorField;

  /**
   * Button Font Color field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.button_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_font_color: prismic.ColorField;

  /**
   * Button Font Size field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.button_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_font_size: prismic.KeyTextField;

  /**
   * Button url field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.button_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_url: prismic.KeyTextField;

  /**
   * Link Button field in *OneColumn → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: one_column.primary.link_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  link_button: prismic.BooleanField;

  /**
   * Justify Items field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.justify_items
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  justify_items: prismic.KeyTextField;

  /**
   * Font color field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Color of title and description
   * - **API ID Path**: one_column.primary.font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  font_color: prismic.ColorField;

  /**
   * KPI Title 1 field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_title_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kpi_title_1: prismic.KeyTextField;

  /**
   * KPI Description 1 field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_description_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kpi_description_1: prismic.KeyTextField;

  /**
   * KPI Color 1 field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_color_1
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  kpi_color_1: prismic.ColorField;

  /**
   * KPI Title 2 field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_title_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kpi_title_2: prismic.KeyTextField;

  /**
   * KPI Description 2 field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_description_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kpi_description_2: prismic.KeyTextField;

  /**
   * KPI Color 2 field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_color_2
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  kpi_color_2: prismic.ColorField;

  /**
   * KPI Title 3 field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_title_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kpi_title_3: prismic.KeyTextField;

  /**
   * KPI Description 3 field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_description_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kpi_description_3: prismic.KeyTextField;

  /**
   * KPI Color 3 field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.kpi_color_3
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  kpi_color_3: prismic.ColorField;

  /**
   * background field in *OneColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;

  /**
   * padding-md field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: one_column.primary.paddingMd
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paddingMd: prismic.KeyTextField;

  /**
   * Margin field in *OneColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: one_column.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for OneColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: OneColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OneColumnSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OneColumn*
 */
type OneColumnSliceVariation = OneColumnSliceDefault;

/**
 * OneColumn Shared Slice
 *
 * - **API ID**: `one_column`
 * - **Description**: OneColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OneColumnSlice = prismic.SharedSlice<
  "one_column",
  OneColumnSliceVariation
>;

/**
 * Primary content in *Partners → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * ID Key field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * title field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * images field in *Partners → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Images Url
   * - **API ID Path**: partners.primary.images
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  images: prismic.RichTextField;

  /**
   * Margin field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: partners.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;

  /**
   * Images Content field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.images_content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  images_content: prismic.KeyTextField;

  /**
   * Title Size field in *Partners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.primary.title_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_size: prismic.KeyTextField;
}

/**
 * Default variation for Partners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partners*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Partners Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Primary content in *PricingCards → Primary*
 */
export interface PricingCardsSliceDefaultPrimary {
  /**
   * Id key field in *PricingCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Title field in *PricingCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Url field in *PricingCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.primary.url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Max Width field in *PricingCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  max_width: prismic.KeyTextField;

  /**
   * Margin field in *PricingCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_cards.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for PricingCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PricingCards*
 */
type PricingCardsSliceVariation = PricingCardsSliceDefault;

/**
 * PricingCards Shared Slice
 *
 * - **API ID**: `pricing_cards`
 * - **Description**: PricingCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingCardsSlice = prismic.SharedSlice<
  "pricing_cards",
  PricingCardsSliceVariation
>;

/**
 * Primary content in *RecommendedCourses → Primary*
 */
export interface RecommendedCoursesSliceDefaultPrimary {
  /**
   * id field in *RecommendedCourses → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_courses.primary.componentId
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  componentId: prismic.KeyTextField;

  /**
   * background field in *RecommendedCourses → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_courses.primary.background
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  background: prismic.KeyTextField;

  /**
   * title field in *RecommendedCourses → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_courses.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * technologies field in *RecommendedCourses → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_courses.primary.technologies
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  technologies: prismic.KeyTextField;

  /**
   * Margin field in *RecommendedCourses → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: recommended_courses.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for RecommendedCourses Slice
 *
 * - **API ID**: `default`
 * - **Description**: RecommendedCourses
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommendedCoursesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecommendedCoursesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RecommendedCourses*
 */
type RecommendedCoursesSliceVariation = RecommendedCoursesSliceDefault;

/**
 * RecommendedCourses Shared Slice
 *
 * - **API ID**: `recommended_courses`
 * - **Description**: RecommendedCourses
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommendedCoursesSlice = prismic.SharedSlice<
  "recommended_courses",
  RecommendedCoursesSliceVariation
>;

/**
 * Primary content in *RoadMap → Primary*
 */
export interface RoadMapSliceDefaultPrimary {
  /**
   * ID Key field in *RoadMap → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: road_map.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Course slug field in *RoadMap → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: road_map.primary.course_slug
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_slug: prismic.KeyTextField;

  /**
   * Title field in *RoadMap → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: road_map.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Margin field in *RoadMap → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: road_map.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for RoadMap Slice
 *
 * - **API ID**: `default`
 * - **Description**: RoadMap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoadMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RoadMapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RoadMap*
 */
type RoadMapSliceVariation = RoadMapSliceDefault;

/**
 * RoadMap Shared Slice
 *
 * - **API ID**: `road_map`
 * - **Description**: RoadMap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RoadMapSlice = prismic.SharedSlice<
  "road_map",
  RoadMapSliceVariation
>;

/**
 * Primary content in *ShowPrices → Primary*
 */
export interface ShowPricesSliceDefaultPrimary {
  /**
   * ID Key field in *ShowPrices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_prices.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Title field in *ShowPrices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_prices.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ShowPrices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_prices.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Plan field in *ShowPrices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_prices.primary.plan
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plan: prismic.KeyTextField;

  /**
   * Bullets field in *ShowPrices → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: show_prices.primary.bullets
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bullets: prismic.RichTextField;

  /**
   * Margin field in *ShowPrices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: show_prices.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for ShowPrices Slice
 *
 * - **API ID**: `default`
 * - **Description**: ShowPrices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowPricesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ShowPricesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ShowPrices*
 */
type ShowPricesSliceVariation = ShowPricesSliceDefault;

/**
 * ShowPrices Shared Slice
 *
 * - **API ID**: `show_prices`
 * - **Description**: ShowPrices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShowPricesSlice = prismic.SharedSlice<
  "show_prices",
  ShowPricesSliceVariation
>;

/**
 * Primary content in *Technologies → Primary*
 */
export interface TechnologiesSliceDefaultPrimary {
  /**
   * ID Key field in *Technologies → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Endpoint field in *Technologies → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies.primary.endpoint
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  endpoint: prismic.KeyTextField;

  /**
   * Margin field in *Technologies → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: technologies.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for Technologies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Technologies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechnologiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TechnologiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Technologies*
 */
type TechnologiesSliceVariation = TechnologiesSliceDefault;

/**
 * Technologies Shared Slice
 *
 * - **API ID**: `technologies`
 * - **Description**: Technologies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechnologiesSlice = prismic.SharedSlice<
  "technologies",
  TechnologiesSliceVariation
>;

/**
 * Primary content in *TechnologiesPills → Primary*
 */
export interface TechnologiesPillsSliceDefaultPrimary {
  /**
   * id field in *TechnologiesPills → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies_pills.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * technologies field in *TechnologiesPills → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies_pills.primary.technologies
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  technologies: prismic.RichTextField;

  /**
   * margin field in *TechnologiesPills → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: technologies_pills.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for TechnologiesPills Slice
 *
 * - **API ID**: `default`
 * - **Description**: TechnologiesPills
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechnologiesPillsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TechnologiesPillsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TechnologiesPills*
 */
type TechnologiesPillsSliceVariation = TechnologiesPillsSliceDefault;

/**
 * TechnologiesPills Shared Slice
 *
 * - **API ID**: `technologies_pills`
 * - **Description**: TechnologiesPills
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TechnologiesPillsSlice = prismic.SharedSlice<
  "technologies_pills",
  TechnologiesPillsSliceVariation
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * ID Key field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Version field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.version
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  version: prismic.KeyTextField;

  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Endpoint field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.endpoint
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  endpoint: prismic.KeyTextField;

  /**
   * Margin field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: testimonials.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TitleIntroduction → Primary*
 */
export interface TitleIntroductionSliceDefaultPrimary {
  /**
   * ID Key field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Two Column Size field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.two_column_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  two_column_size: prismic.SelectField<
    "Left is bigger" | "Both are equal" | "Right is bigger"
  >;

  /**
   * Title field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: title_introduction.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * buttonText field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.buttontext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttontext: prismic.RichTextField;

  /**
   * Button link field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_link: prismic.KeyTextField;

  /**
   * highlight field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.highlight
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  highlight: prismic.RichTextField;

  /**
   * Highlight Style field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.highlight_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  highlight_style: prismic.SelectField<"Underlined" | "Colored">;

  /**
   * description field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * bullets field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.bullets
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bullets: prismic.RichTextField;

  /**
   * image field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Margin field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: title_introduction.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;

  /**
   * Grid gap field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Space between columns in pixels
   * - **API ID Path**: title_introduction.primary.grid_gap
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  grid_gap: prismic.KeyTextField;

  /**
   * Font Family field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Lato
   * - **API ID Path**: title_introduction.primary.fontFamily
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  fontFamily: prismic.SelectField<"Lato" | "Space Grotesk Variable", "filled">;

  /**
   * Button Id field in *TitleIntroduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_introduction.primary.button_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_id: prismic.KeyTextField;
}

/**
 * Default variation for TitleIntroduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: TitleIntroduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleIntroductionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleIntroductionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleIntroduction*
 */
type TitleIntroductionSliceVariation = TitleIntroductionSliceDefault;

/**
 * TitleIntroduction Shared Slice
 *
 * - **API ID**: `title_introduction`
 * - **Description**: TitleIntroduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleIntroductionSlice = prismic.SharedSlice<
  "title_introduction",
  TitleIntroductionSliceVariation
>;

/**
 * Primary content in *TrustCards → Primary*
 */
export interface TrustCardsSliceDefaultPrimary {
  /**
   * title field in *TrustCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *TrustCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_cards.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Font Family field in *TrustCards → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: trust_cards.primary.fontFamily
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  fontFamily: prismic.SelectField<"Lato" | "Space Grotesk Variable">;
}

/**
 * Default variation for TrustCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrustCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrustCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TrustCards*
 */
type TrustCardsSliceVariation = TrustCardsSliceDefault;

/**
 * TrustCards Shared Slice
 *
 * - **API ID**: `trust_cards`
 * - **Description**: TrustCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrustCardsSlice = prismic.SharedSlice<
  "trust_cards",
  TrustCardsSliceVariation
>;

/**
 * Primary content in *TwoColumn → Primary*
 */
export interface TwoColumnSliceDefaultPrimary {
  /**
   * ID Key field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.id_key
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  id_key: prismic.KeyTextField;

  /**
   * Information Size field in *TwoColumn → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Proportion of sizes
   * - **API ID Path**: two_column.primary.information_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  information_size: prismic.SelectField<"Small" | "Medium" | "Large">;

  /**
   * Border Radius field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.border_radius
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  border_radius: prismic.KeyTextField;

  /**
   * Max Width field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.max_width
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  max_width: prismic.KeyTextField;

  /**
   * Margin field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: top, right, bottom, left
   * - **API ID Path**: two_column.primary.margin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin: prismic.KeyTextField;

  /**
   * Margin Top field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.margin_top
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_top: prismic.KeyTextField;

  /**
   * Margin Bottom field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.margin_bottom
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  margin_bottom: prismic.KeyTextField;

  /**
   * Text Background Color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.text_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  text_background_color: prismic.ColorField;

  /**
   * Title field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Custom Title Size field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.custom_title_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_title_size: prismic.KeyTextField;

  /**
   * Font Family Title field in *TwoColumn → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Lato
   * - **API ID Path**: two_column.primary.fontFamily
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  fontFamily: prismic.SelectField<"Lato" | "Space Grotesk Variable", "filled">;

  /**
   * Title Color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.title_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  title_color: prismic.ColorField;

  /**
   * Subtitle field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Custom Subtitle Size field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.custom_subtitle_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  custom_subtitle_size: prismic.KeyTextField;

  /**
   * Font Family Subtitle field in *TwoColumn → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.font_family_subtitle
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  font_family_subtitle: prismic.SelectField<"Lato" | "Space Grotesk Variable">;

  /**
   * Subtitle Color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.subtitle_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  subtitle_color: prismic.ColorField;

  /**
   * Description Title field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.description_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_title: prismic.KeyTextField;

  /**
   * Description field in *TwoColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Description Color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.description_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  description_color: prismic.ColorField;

  /**
   * Description Font Size field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.description_font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_font_size: prismic.KeyTextField;

  /**
   * image field in *TwoColumn → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Students Avatars field in *TwoColumn → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.students_avatars
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  students_avatars: prismic.RichTextField;

  /**
   * Students Avatars Descriptions field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.student_avatar_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  student_avatar_description: prismic.KeyTextField;

  /**
   * Button label field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Label Size field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.button_label_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label_size: prismic.KeyTextField;

  /**
   * Button url field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.button_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_url: prismic.KeyTextField;

  /**
   * Link Button field in *TwoColumn → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_column.primary.link_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  link_button: prismic.BooleanField;

  /**
   * Font color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  font_color: prismic.ColorField;

  /**
   * Font color in darkmode field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.font_color_in_darkmode
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  font_color_in_darkmode: prismic.ColorField;

  /**
   * Button Color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<"Blue" | "White" | "Dark Blue">;

  /**
   * Background color field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Example: #FFFFFF
   * - **API ID Path**: two_column.primary.background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_color: prismic.ColorField;

  /**
   * Background in dark mode field in *TwoColumn → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.background_in_dark_mode
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background_in_dark_mode: prismic.ColorField;

  /**
   * Image position field in *TwoColumn → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.image_position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_position: prismic.SelectField<"left" | "right">;

  /**
   * Grid gap field in *TwoColumn → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.primary.grid_gap
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  grid_gap: prismic.KeyTextField;

  /**
   * Transparent field in *TwoColumn → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_column.primary.transparent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  transparent: prismic.BooleanField;
}

/**
 * Primary content in *TwoColumn → Items*
 */
export interface TwoColumnSliceDefaultItem {
  /**
   * Multi Description Title field in *TwoColumn → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.items[].multi_description_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  multi_description_title: prismic.KeyTextField;

  /**
   * Multi Description Content field in *TwoColumn → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column.items[].multi_description_content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  multi_description_content: prismic.KeyTextField;
}

/**
 * Default variation for TwoColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: TwoColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColumnSliceDefaultPrimary>,
  Simplify<TwoColumnSliceDefaultItem>
>;

/**
 * Slice variation for *TwoColumn*
 */
type TwoColumnSliceVariation = TwoColumnSliceDefault;

/**
 * TwoColumn Shared Slice
 *
 * - **API ID**: `two_column`
 * - **Description**: TwoColumn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnSlice = prismic.SharedSlice<
  "two_column",
  TwoColumnSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      EventCardsSlice,
      EventCardsSliceDefaultPrimary,
      EventCardsSliceVariation,
      EventCardsSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimary,
      FaqsSliceDefaultItem,
      FaqsSliceVariation,
      FaqsSliceDefault,
      InfoCardsSlice,
      InfoCardsSliceDefaultPrimary,
      InfoCardsSliceVariation,
      InfoCardsSliceDefault,
      MarkdownSlice,
      MarkdownSliceDefaultPrimary,
      MarkdownSliceVariation,
      MarkdownSliceDefault,
      MultipleColumnCardSlice,
      MultipleColumnCardSliceDefaultPrimary,
      MultipleColumnCardSliceDefaultItem,
      MultipleColumnCardSliceVariation,
      MultipleColumnCardSliceDefault,
      OneColumnSlice,
      OneColumnSliceDefaultPrimary,
      OneColumnSliceVariation,
      OneColumnSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      PricingCardsSlice,
      PricingCardsSliceDefaultPrimary,
      PricingCardsSliceVariation,
      PricingCardsSliceDefault,
      RecommendedCoursesSlice,
      RecommendedCoursesSliceDefaultPrimary,
      RecommendedCoursesSliceVariation,
      RecommendedCoursesSliceDefault,
      RoadMapSlice,
      RoadMapSliceDefaultPrimary,
      RoadMapSliceVariation,
      RoadMapSliceDefault,
      ShowPricesSlice,
      ShowPricesSliceDefaultPrimary,
      ShowPricesSliceVariation,
      ShowPricesSliceDefault,
      TechnologiesSlice,
      TechnologiesSliceDefaultPrimary,
      TechnologiesSliceVariation,
      TechnologiesSliceDefault,
      TechnologiesPillsSlice,
      TechnologiesPillsSliceDefaultPrimary,
      TechnologiesPillsSliceVariation,
      TechnologiesPillsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TitleIntroductionSlice,
      TitleIntroductionSliceDefaultPrimary,
      TitleIntroductionSliceVariation,
      TitleIntroductionSliceDefault,
      TrustCardsSlice,
      TrustCardsSliceDefaultPrimary,
      TrustCardsSliceVariation,
      TrustCardsSliceDefault,
      TwoColumnSlice,
      TwoColumnSliceDefaultPrimary,
      TwoColumnSliceDefaultItem,
      TwoColumnSliceVariation,
      TwoColumnSliceDefault,
    };
  }
}
