// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Learn to code documents */
interface LearnToCodeDocumentData {
    /**
     * Title field in *Learn to code*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: learn_to_code.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Learn to code document from Prismic
 *
 * - **API ID**: `learn_to_code`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LearnToCodeDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<LearnToCodeDocumentData>, "learn_to_code", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = LearnToCodeDocument | PageDocument;
/**
 * Primary content in TitleIntroduction → Primary
 *
 */
interface TitleIntroductionSliceDefaultPrimary {
    /**
     * Title field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: title_introduction.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * buttonText field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    buttontext: prismicT.RichTextField;
    /**
     * highlight field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.highlight
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlight: prismicT.RichTextField;
    /**
     * description field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * bullets field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.bullets
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    bullets: prismicT.RichTextField;
}
/**
 * Default variation for TitleIntroduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleIntroduction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleIntroductionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleIntroductionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TitleIntroduction*
 *
 */
type TitleIntroductionSliceVariation = TitleIntroductionSliceDefault;
/**
 * TitleIntroduction Shared Slice
 *
 * - **API ID**: `title_introduction`
 * - **Description**: `TitleIntroduction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleIntroductionSlice = prismicT.SharedSlice<"title_introduction", TitleIntroductionSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { LearnToCodeDocumentData, LearnToCodeDocument, PageDocumentData, PageDocument, AllDocumentTypes, TitleIntroductionSliceDefaultPrimary, TitleIntroductionSliceDefault, TitleIntroductionSliceVariation, TitleIntroductionSlice };
    }
}
