// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * TItle field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Description for Social Cards
     * - **API ID Path**: page.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * type field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The default type is "website"
     * - **API ID Path**: page.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = TitleIntroductionSlice | MarkdownSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = PageDocument;
/**
 * Primary content in Markdown → Primary
 *
 */
interface MarkdownSliceDefaultPrimary {
    /**
     * Title field in *Markdown → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: markdown.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Description field in *Markdown → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: markdown.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Markdown field in *Markdown → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: markdown.primary.markdown
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    markdown: prismicT.RichTextField;
    /**
     * Enable Table of Content field in *Markdown → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: markdown.primary.enable_table_of_content
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    enable_table_of_content: prismicT.BooleanField;
}
/**
 * Default variation for Markdown Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Markdown`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MarkdownSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MarkdownSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Markdown*
 *
 */
type MarkdownSliceVariation = MarkdownSliceDefault;
/**
 * Markdown Shared Slice
 *
 * - **API ID**: `markdown`
 * - **Description**: `Markdown`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MarkdownSlice = prismicT.SharedSlice<"markdown", MarkdownSliceVariation>;
/**
 * Primary content in TitleIntroduction → Primary
 *
 */
interface TitleIntroductionSliceDefaultPrimary {
    /**
     * Title field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: title_introduction.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * buttonText field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    buttontext: prismicT.RichTextField;
    /**
     * highlight field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.highlight
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    highlight: prismicT.RichTextField;
    /**
     * description field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * bullets field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.bullets
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    bullets: prismicT.RichTextField;
    /**
     * image field in *TitleIntroduction → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: title_introduction.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for TitleIntroduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleIntroduction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleIntroductionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleIntroductionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TitleIntroduction*
 *
 */
type TitleIntroductionSliceVariation = TitleIntroductionSliceDefault;
/**
 * TitleIntroduction Shared Slice
 *
 * - **API ID**: `title_introduction`
 * - **Description**: `TitleIntroduction`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleIntroductionSlice = prismicT.SharedSlice<"title_introduction", TitleIntroductionSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, MarkdownSliceDefaultPrimary, MarkdownSliceDefault, MarkdownSliceVariation, MarkdownSlice, TitleIntroductionSliceDefaultPrimary, TitleIntroductionSliceDefault, TitleIntroductionSliceVariation, TitleIntroductionSlice };
    }
}
