// Code generated by Slice Machine. DO NOT EDIT.

import Markdown from './Markdown';
import OneColumn from './OneColumn';
import Partners from './Partners';
import ShowPrices from './ShowPrices';
import Testimonials from './Testimonials';
import TitleIntroduction from './TitleIntroduction';
import TwoColumn from './TwoColumn';

export {
	Markdown,
	OneColumn,
	Partners,
	ShowPrices,
	Testimonials,
	TitleIntroduction,
	TwoColumn,
};

export const components = {
	markdown: Markdown,
	one_column: OneColumn,
	partners: Partners,
	show_prices: ShowPrices,
	testimonials: Testimonials,
	title_introduction: TitleIntroduction,
	two_column: TwoColumn,
};
