// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  event_cards: dynamic(() => import("./EventCards")),
  info_cards: dynamic(() => import("./InfoCards")),
  markdown: dynamic(() => import("./Markdown")),
  one_column: dynamic(() => import("./OneColumn")),
  partners: dynamic(() => import("./Partners")),
  recommended_courses: dynamic(() => import("./RecommendedCourses")),
  road_map: dynamic(() => import("./RoadMap")),
  show_prices: dynamic(() => import("./ShowPrices")),
  technologies: dynamic(() => import("./Technologies")),
  technologies_pills: dynamic(() => import("./TechnologiesPills")),
  testimonials: dynamic(() => import("./Testimonials")),
  title_introduction: dynamic(() => import("./TitleIntroduction")),
  trust_cards: dynamic(() => import("./TrustCards")),
  two_column: dynamic(() => import("./TwoColumn")),
};
