// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  award_section: dynamic(() => import("./AwardSection")),
  event_cards: dynamic(() => import("./EventCards")),
  event_toast: dynamic(() => import("./EventToast")),
  faqs: dynamic(() => import("./Faqs")),
  hero_section: dynamic(() => import("./HeroSection")),
  info_cards: dynamic(() => import("./InfoCards")),
  learning_platform_section: dynamic(() => import("./LearningPlatformSection")),
  markdown: dynamic(() => import("./Markdown")),
  multiple_column_card: dynamic(() => import("./MultipleColumnCard")),
  one_column: dynamic(() => import("./OneColumn")),
  outcomes: dynamic(() => import("./Outcomes")),
  page_bubble: dynamic(() => import("./PageBubble")),
  partners: dynamic(() => import("./Partners")),
  pricing_cards: dynamic(() => import("./PricingCards")),
  product_pricing: dynamic(() => import("./ProductPricing")),
  ratings: dynamic(() => import("./Ratings")),
  recommended_courses: dynamic(() => import("./RecommendedCourses")),
  road_map: dynamic(() => import("./RoadMap")),
  show_prices: dynamic(() => import("./ShowPrices")),
  split_showcase_section: dynamic(() => import("./SplitShowcaseSection")),
  technologies: dynamic(() => import("./Technologies")),
  technologies_pills: dynamic(() => import("./TechnologiesPills")),
  testimonials: dynamic(() => import("./Testimonials")),
  title_introduction: dynamic(() => import("./TitleIntroduction")),
  trust_cards: dynamic(() => import("./TrustCards")),
  two_column: dynamic(() => import("./TwoColumn")),
  two_column_with_text: dynamic(() => import("./TwoColumnWithText")),
};
