const NEXT_STEP = 'NEXT_STEP';
const PREV_STEP = 'PREV_STEP';
const HANDLE_STEP = 'HANDLE_STEP';
const SET_DATE_PROPS = 'SET_DATE_PROPS';
const SET_CHECKOUT_DATA = 'SET_CHECKOUT_DATA';
const SET_PAYMENT_INFO = 'SET_PAYMENT_INFO';
const HANDLE_PAYMENT = 'HANDLE_PAYMENT';
const SET_PLAN_DATA = 'SET_PLAN_DATA';
const SET_LOADER = 'SET_LOADER';
const SET_PLAN_CHECKOUT_DATA = 'SET_PLAN_CHECKOUT_DATA';
const SET_PLAN_PROPS = 'SET_PLAN_PROPS';
const SET_COHORT_PLANS = 'SET_COHORT_PLANS';
const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION';
const TOGGLE_IF_ENROLLED = 'TOGGLE_IF_ENROLLED';
const IS_LOADING = 'IS_LOADING';
const SET_SERVICE_PROPS = 'SET_SERVICE_PROPS';
const SET_SELECTED_SERVICE = 'SET_SELECTED_SERVICE';
const SET_PAYMENT_METHODS = 'SET_PAYMENT_METHODS';
const SET_PAYMENT_STATUS = 'SET_PAYMENT_STATUS';
const SET_SUBMITTING_CARD = 'SET_SUBMITTING_CARD';
const SET_SUBMITTING_PAYMENT = 'SET_SUBMITTING_PAYMENT';
const SET_SELF_APPLIED_COUPON = 'SET_SELF_APPLIED_COUPON';
const SET_COHORTS_ASSIGNMENTS = 'SET_COHORTS_ASSIGNMENTS';
const SET_COHORT_SESSION = 'SET_COHORT_SESSION';
const SET_TASK_COHORT_NULL = 'SET_TASK_COHORT_NULL';
const SET_USER_CAPABILITIES = 'SET_USER_CAPABILITIES';
const SET_REVIEW_MODAL_STATE = 'SET_REVIEW_MODAL_STATE';
const SET_STAGE_HISTORY = 'SET_STAGE_HISTORY';

// For conditional types
const PREPARING_FOR_COHORT = 'PREPARING_FOR_COHORT';

export {
  NEXT_STEP,
  PREV_STEP,
  HANDLE_STEP,
  SET_DATE_PROPS,
  SET_CHECKOUT_DATA,
  SET_PAYMENT_INFO,
  SET_PAYMENT_STATUS,
  SET_SUBMITTING_CARD,
  SET_SUBMITTING_PAYMENT,
  HANDLE_PAYMENT,
  SET_PLAN_DATA,
  SET_LOADER,
  SET_PLAN_CHECKOUT_DATA,
  SET_PLAN_PROPS,
  SET_COHORT_PLANS,
  FETCH_SUBSCRIPTIONS,
  CANCEL_SUBSCRIPTION,
  TOGGLE_IF_ENROLLED,
  IS_LOADING,
  PREPARING_FOR_COHORT,
  SET_SERVICE_PROPS,
  SET_SELECTED_SERVICE,
  SET_PAYMENT_METHODS,
  SET_COHORTS_ASSIGNMENTS,
  SET_COHORT_SESSION,
  SET_TASK_COHORT_NULL,
  SET_USER_CAPABILITIES,
  SET_REVIEW_MODAL_STATE,
  SET_STAGE_HISTORY,
  SET_SELF_APPLIED_COUPON,
};
