const NEXT_STEP = 'NEXT_STEP';
const PREV_STEP = 'PREV_STEP';
const HANDLE_STEP = 'HANDLE_STEP';
const SET_DATE_PROPS = 'SET_DATE_PROPS';
const SET_CHECKOUT_DATA = 'SET_CHECKOUT_DATA';
const SET_LOCATION = 'SET_LOCATION';
const SET_PAYMENT_INFO = 'SET_PAYMENT_INFO';
const HANDLE_PAYMENT = 'HANDLE_PAYMENT';
const SET_PLAN_DATA = 'SET_PLAN_DATA';
const SET_LOADER = 'SET_LOADER';
const SET_PLAN_CHECKOUT_DATA = 'SET_PLAN_CHECKOUT_DATA';
const SET_PLAN_PROPS = 'SET_PLAN_PROPS';
const SET_COHORT_PLANS = 'SET_COHORT_PLANS';
const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION';

export {
  NEXT_STEP,
  PREV_STEP,
  HANDLE_STEP,
  SET_DATE_PROPS,
  SET_CHECKOUT_DATA,
  SET_LOCATION,
  SET_PAYMENT_INFO,
  HANDLE_PAYMENT,
  SET_PLAN_DATA,
  SET_LOADER,
  SET_PLAN_CHECKOUT_DATA,
  SET_PLAN_PROPS,
  SET_COHORT_PLANS,
  FETCH_SUBSCRIPTIONS,
  CANCEL_SUBSCRIPTION,
};
